name: chat_app_mobile_client
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.1 # for State management
  intl: ^0.17.0
  shared_preferences: ^2.0.9
  fuzzy: ^0.4.0-nullsafety.0 #search
  auto_animated: ^3.0.1

  flutter_slidable: ^1.1.0 #swip to delete

  flutter_svg: ^0.23.0 # help us to use SVG in our app
  image_picker: ^0.8.4+4 #image and video picker
  video_player: ^2.2.7 #video player

  
  # network
  http: ^0.13.4

  #hash pass
  crypto: ^3.0.1

  #socket io
  socket_io_client: ^2.0.0-beta.4-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  flutter_launcher_icons: ^0.9.1

flutter_icons:
  image_path: "assets/images/large_logo.png"
  android: true
  ios: true

flutter_assets:
  assets_path: assets/
  output_path: lib/constants/
  filename: assets.dart

flutter:
  uses-material-design: true

  assets:
   - assets/
   - assets/images/
   - assets/icons/

  fonts:
  - family: ProductSans
    fonts:
    - asset: assets/fonts/Product-Sans-Regular.ttf
    - asset: assets/fonts/Product-Sans-Italic.ttf
      style: italic
    - asset: assets/fonts/Product-Sans-Bold.ttf
      weight: 700
      
flutter_intl:
  enabled: true
  